"""AI provider registry for VibeCode Translator."""

PROVIDERS = [
    {
        "id": "claude",
        "label": "Claude (Anthropic)",
        "type": "anthropic",
        "model": "claude-sonnet-4-6",
        "key_placeholder": "sk-ant-...",
        "requires_key": True,
    },
    {
        "id": "openai",
        "label": "GPT (OpenAI)",
        "type": "openai",
        "model": "gpt-4o",
        "key_placeholder": "sk-...",
        "requires_key": True,
    },
    {
        "id": "openrouter",
        "label": "OpenRouter",
        "type": "openai_compatible",
        "base_url": "https://openrouter.ai/api/v1",
        "model": "anthropic/claude-sonnet-4",
        "key_placeholder": "sk-or-...",
        "requires_key": True,
        "extra_headers": {
            "HTTP-Referer": "https://github.com/louisty2006/VibeCode_Translator",
            "X-Title": "VibeCode Translator",
        },
    },
    {
        "id": "gemini",
        "label": "Gemini (Google)",
        "type": "openai_compatible",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai/",
        "model": "gemini-2.0-flash",
        "key_placeholder": "AIza...",
        "requires_key": True,
    },
    {
        "id": "groq",
        "label": "Groq",
        "type": "openai_compatible",
        "base_url": "https://api.groq.com/openai/v1",
        "model": "llama-3.3-70b-versatile",
        "key_placeholder": "gsk_...",
        "requires_key": True,
    },
    {
        "id": "mistral",
        "label": "Mistral AI",
        "type": "openai_compatible",
        "base_url": "https://api.mistral.ai/v1",
        "model": "mistral-large-latest",
        "key_placeholder": "...",
        "requires_key": True,
    },
    {
        "id": "deepseek",
        "label": "DeepSeek",
        "type": "openai_compatible",
        "base_url": "https://api.deepseek.com",
        "model": "deepseek-chat",
        "key_placeholder": "sk-...",
        "requires_key": True,
    },
    {
        "id": "cohere",
        "label": "Cohere",
        "type": "openai_compatible",
        "base_url": "https://api.cohere.com/compatibility/v1",
        "model": "command-r-plus-08-2024",
        "key_placeholder": "...",
        "requires_key": True,
    },
    {
        "id": "together",
        "label": "Together AI",
        "type": "openai_compatible",
        "base_url": "https://api.together.xyz/v1",
        "model": "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
        "key_placeholder": "...",
        "requires_key": True,
    },
    {
        "id": "xai",
        "label": "Grok (xAI)",
        "type": "openai_compatible",
        "base_url": "https://api.x.ai/v1",
        "model": "grok-2-latest",
        "key_placeholder": "xai-...",
        "requires_key": True,
    },
    {
        "id": "fireworks",
        "label": "Fireworks AI",
        "type": "openai_compatible",
        "base_url": "https://api.fireworks.ai/inference/v1",
        "model": "accounts/fireworks/models/llama-v3p1-70b-instruct",
        "key_placeholder": "fw_...",
        "requires_key": True,
    },
    {
        "id": "ollama",
        "label": "Ollama (Local)",
        "type": "openai_compatible",
        "base_url": "http://localhost:11434/v1",
        "model": "llama3.2",
        "key_placeholder": "not required",
        "requires_key": False,
    },
]

PROVIDER_BY_ID = {p["id"]: p for p in PROVIDERS}

DEFAULT_PROVIDER_ID = "claude"
